version: '1.0'
stages:
  - prepare
  - build

steps:
  clone:
    title: Cloning repository
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: prepare

  build_docker_image:
    title: Building Docker image
    type: build
    image_name: '${{CF_REPO_NAME}}'
    working_directory: '${{CF_REPO_NAME}}'
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: Dockerfile
    stage: build
    build_arguments:
      - REPO_NAME=${{CF_REPO_NAME}}

  run_tests:
    title: Running tests
    image: '${{build_docker_image}}'
    commands:
      - printenv
