export const AUTOBLOCKS_WEBAPP_BASE_URL = 'https://app.autoblocks.ai';
export const AUTOBLOCKS_API_BASE_URL = 'https://api.autoblocks.ai';
export const AUTOBLOCKS_API_KEY_NAME = 'AUTOBLOCKS_API_KEY';
export const AUTOBLOCKS_TEST_RUN_MESSAGE_NAME = 'AUTOBLOCKS_TEST_RUN_MESSAGE';
export const AUTOBLOCKS_SLACK_WEBHOOK_URL_NAME = 'AUTOBLOCKS_SLACK_WEBHOOK_URL';
