import { Box, Text } from 'ink';
import { type AutogeneratedEvaluatorWithFilepath } from '../util/models';

export function AutogeneratedEvaluatorsList(props: {
  evaluators: AutogeneratedEvaluatorWithFilepath[];
}) {
  return (
    <Box flexDirection="column">
      <Text>Generated {props.evaluators.length} evaluators:</Text>
      <Box columnGap={1}>
        <Box flexDirection="column">
          {props.evaluators.map((evaluator) => {
            return (
              <Box key={evaluator.id} columnGap={1}>
                <Text color="green">{'→'}</Text>
                <Text bold={true}>{evaluator.id}</Text>
              </Box>
            );
          })}
        </Box>
        <Box flexDirection="column">
          {props.evaluators.map((evaluator) => {
            return (
              <Box key={evaluator.id}>
                <Text color="gray">{evaluator.filepath}</Text>
              </Box>
            );
          })}
        </Box>
      </Box>
    </Box>
  );
}
