name: CI

on: push

# Cancel in progress runs of this workflow when we push changes to the branch
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AUTOBLOCKS_API_KEY: ${{ secrets.AUTOBLOCKS_API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TSUP_PUBLIC_AUTOBLOCKS_INGESTION_KEY: test

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - '18'
          - '20'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Validate renovate config
        run: npx --package renovate renovate-config-validator --strict

      - name: Install dependencies
        run: npm ci

      - name: Fixup ink types
        run: bash ./tools/fixup-ink-types.sh

      - name: Run type checks
        run: npm run type-check

      - name: Run lint checks
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Run testing exec
        run: npx autoblocks testing exec -- echo "hi"
