name: E2E

on:
  # Run on different types of events to ensure we are
  # handling the git data correctly in each scenario
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      autoblocks-overrides:
        type: string
        description: Overrides for Autoblocks-managed entities
        required: false
  schedule:
    - cron: '17 15 * * *'

jobs:
  py:
    name: python-e2e-${{ github.event_name }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # For debugging purposes
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CLI dependencies
        run: npm ci

      - name: Build CLI
        run: npm run build

      - name: Install dependencies in e2e/python
        run: pip install -r requirements.txt
        working-directory: e2e/python

      # Set the AUTOBLOCKS_SLACK_WEBHOOK_URL environment variable
      # if this workflow was triggered by a scheduled run, since
      # we only want to post to Slack on scheduled runs and not on
      # every push or pull request.
      - name: Set Slack webhook URL
        run: echo "AUTOBLOCKS_SLACK_WEBHOOK_URL=${{ secrets.ADAM_TEST_SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV

      - name: Make CI context
        run: ../../bin/cli.js testing make-ci-context
        working-directory: e2e/python
        env:
          AUTOBLOCKS_API_KEY: ${{ secrets.AUTOBLOCKS_API_KEY }}

      - name: Run tests in e2e/python
        run: python3 run.py
        working-directory: e2e/python
        env:
          PYTHONPATH: ${{ github.workspace }}/e2e/python
          FORCE_COLOR: 3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTOBLOCKS_API_KEY: ${{ secrets.AUTOBLOCKS_API_KEY }}

  ts:
    name: typescript-e2e-${{ github.event_name }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # For debugging purposes
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CLI dependencies
        run: npm ci

      - name: Build CLI
        run: npm run build

      - name: Install dependencies in e2e/typescript
        run: npm install
        working-directory: e2e/typescript

      # Set the AUTOBLOCKS_SLACK_WEBHOOK_URL environment variable
      # if this workflow was triggered by a scheduled run, since
      # we only want to post to Slack on scheduled runs and not on
      # every push or pull request.
      - name: Set Slack webhook URL
        if: github.event_name == 'schedule'
        run: echo "AUTOBLOCKS_SLACK_WEBHOOK_URL=${{ secrets.AUTOBLOCKS_SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV

      - name: Run tests in e2e/typescript
        run: ../../bin/cli.js testing exec -- npx tsx run.ts
        working-directory: e2e/typescript
        env:
          FORCE_COLOR: 3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTOBLOCKS_API_KEY: ${{ secrets.AUTOBLOCKS_API_KEY }}

  notify:
    needs:
      - py
      - ts

    if: always() && contains(needs.*.result, 'failure') && github.event_name == 'schedule'

    runs-on: ubuntu-latest

    steps:
      - uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": ":warning:  Workflow `${{ github.workflow }}` in repository `${{ github.repository }}` failed. <${{ env.run-url }}|Logs>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.AUTOBLOCKS_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

          run-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
