name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Fixup ink types
        run: bash ./tools/fixup-ink-types.sh

      - name: Set version in package.json
        run: npm version ${{ inputs.version }} --no-git-tag-version

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # also publish under name "autoblocks"
      - name: Change package name
        run: |
          jq '.name = "autoblocks"' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push tag to GitHub
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@autoblocks.ai'
          git tag -a ${{ inputs.version }} -m "${{ inputs.version }}"
          git push origin ${{ inputs.version }}
